# -*- encoding: utf-8 -*-

=begin
#Zenodo API

#This is for the zenodo API http://developers.zenodo.org/#rest-api

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.8

=end

$:.push File.expand_path("../lib", __FILE__)
require "zenodo_client/version"

Gem::Specification.new do |s|
  s.name        = "zenodo_client"
  s.version     = ZenodoClient::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["Pierre Rioux"]
  s.email       = ["pierre.rioux@mcgill.ca"]
  s.homepage    = "https://github.com/aces/zenodo-client-gem"
  s.summary     = "Zenodo API"
  s.description = "This gem implements the Zenodo API"
  s.license     = 'GPL-3.0'
  s.required_ruby_version = ">= 2.4.1"

  s.add_runtime_dependency 'typhoeus', '~> 1.0', '>= 1.0.1'
  s.add_runtime_dependency 'json', '~> 2.1', '>= 2.1.0'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'
  s.add_development_dependency 'vcr', '~> 3.0', '>= 3.0.1'
  s.add_development_dependency 'webmock', '~> 1.24', '>= 1.24.3'
  s.add_development_dependency 'autotest', '~> 4.4', '>= 4.4.6'
  s.add_development_dependency 'autotest-rails-pure', '~> 4.1', '>= 4.1.2'
  s.add_development_dependency 'autotest-growl', '~> 0.2', '>= 0.2.16'
  s.add_development_dependency 'autotest-fsevent', '~> 0.2', '>= 0.2.12'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
