=begin
#Zenodo API

#This is for the zenodo API http://developers.zenodo.org/#rest-api

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.8

=end

require 'spec_helper'
require 'json'

# Unit tests for ZenodoClient::ActionsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ActionsApi' do
  before do
    # run before each test
    @instance = ZenodoClient::ActionsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ActionsApi' do
    it 'should create an instance of ActionsApi' do
      expect(@instance).to be_instance_of(ZenodoClient::ActionsApi)
    end
  end

  # unit tests for discard_deposit
  # Discard changes in the current editing session.
  # Untested swagger description
  # @param deposit_id 
  # @param [Hash] opts the optional parameters
  # @return [Deposit]
  describe 'discard_deposit test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for edit_deposit
  # Unlock already submitted deposition for editing.
  # Untested swagger description
  # @param deposit_id 
  # @param [Hash] opts the optional parameters
  # @return [Deposit]
  describe 'edit_deposit test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for new_deposit_version
  # Create a new version of a deposition.
  # Untested swagger description
  # @param deposit_id 
  # @param [Hash] opts the optional parameters
  # @return [Deposit]
  describe 'new_deposit_version test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for publish_deposit
  # Publish a deposition. Note, once a deposition is published, you can no longer delete it.
  # Untested swagger description
  # @param deposit_id 
  # @param [Hash] opts the optional parameters
  # @return [Deposit]
  describe 'publish_deposit test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
