=begin
#Zenodo API

#This is for the zenodo API http://developers.zenodo.org/#rest-api

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.8

=end

require 'spec_helper'
require 'json'

# Unit tests for ZenodoClient::DepositsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'DepositsApi' do
  before do
    # run before each test
    @instance = ZenodoClient::DepositsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DepositsApi' do
    it 'should create an instance of DepositsApi' do
      expect(@instance).to be_instance_of(ZenodoClient::DepositsApi)
    end
  end

  # unit tests for create_deposit
  # Create a new deposit
  # 
  # @param deposit The deposit to create.
  # @param [Hash] opts the optional parameters
  # @return [Deposit]
  describe 'create_deposit test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_deposit
  # Delete deposit
  # Delete a single deposit
  # @param deposit_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_deposit test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_deposit
  # Get deposit
  # Get a single deposit
  # @param deposit_id 
  # @param [Hash] opts the optional parameters
  # @return [Deposit]
  describe 'get_deposit test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_deposits
  # List of deposits
  # 
  # @param [Hash] opts the optional parameters
  # @return [Array<Deposit>]
  describe 'list_deposits test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for put_deposit
  # Put deposit
  # Update metadata for a single deposit
  # @param deposit_id 
  # @param deposit The deposit to update.
  # @param [Hash] opts the optional parameters
  # @return [Deposit]
  describe 'put_deposit test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
