=begin
#Zenodo API

#This is for the zenodo API http://developers.zenodo.org/#rest-api

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.8

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for ZenodoClient::NestedDepositMetadata
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'NestedDepositMetadata' do
  before do
    # run before each test
    @instance = ZenodoClient::NestedDepositMetadata.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of NestedDepositMetadata' do
    it 'should create an instance of NestedDepositMetadata' do
      expect(@instance).to be_instance_of(ZenodoClient::NestedDepositMetadata)
    end
  end
  describe 'test attribute "metadata"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
