=begin
#Zenodo API

#This is for the zenodo API http://developers.zenodo.org/#rest-api

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.8

=end

# Common files
require 'zenodo_client/api_client'
require 'zenodo_client/api_error'
require 'zenodo_client/version'
require 'zenodo_client/configuration'

# Models
require 'zenodo_client/models/author'
require 'zenodo_client/models/community'
require 'zenodo_client/models/contributor'
require 'zenodo_client/models/deposit'
require 'zenodo_client/models/deposit_metadata'
require 'zenodo_client/models/deposition_file'
require 'zenodo_client/models/grant'
require 'zenodo_client/models/nested_deposit_metadata'
require 'zenodo_client/models/related_identifier'
require 'zenodo_client/models/subject'
require 'zenodo_client/models/upload_file'

# APIs
require 'zenodo_client/api/actions_api'
require 'zenodo_client/api/deposits_api'
require 'zenodo_client/api/files_api'
require 'zenodo_client/api/preview_api'

module ZenodoClient
  class << self
    # Customize default settings for the SDK using block.
    #   ZenodoClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
